add authorized ssh keys on build
waterloop/WLoopOS pull request #3
Opened 2022-10-15 07:35 UTC by ethanckim

2022-10-15 07:39 UTC, ethanckim commented on wloop_os/board/rpi4/authorized_keys
> +ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBRr2oSX5UJ5+R92xmoAxSz5qcu8teh6tLn3x4VHdLUp Ethans Ubuntu
The idea is to add authorized ssh keys on this file (eg. ssh-keygen generated from my computer), and after running the build, this file will exist in `/root/.ssh/authorized_keys`.

Let me know if adding a comment here would be a better practice (or add this file to the .gitignore), rather than exposing the keys in a public repo. I think it is safe to do this as it is the public key that is being exposed, not the private key.

2022-10-15 07:57 UTC, RyanJMah requested changes
This is a good start, but its not quite there yet.

The ticket mentions generating keys on compile time, which can be done with
```
ssh-keygen -f <OUTPUT_PATH>
```

I would recommend having the `post-build.sh` use `ssh-keygen` to generate keys in the ./build directory, then copying the generated public key to `authorized_keys`. You can also copy your host's public key (if you want).

This method also doesn't require having plaintext keys on GitHub (even if they are public keys, still probably not a best practice).

2022-10-17 03:03 UTC, RyanJMah commented
Task linked: [CU-30jh0wc Add default ssh key to WLoopOS](https://app.clickup.com/t/30jh0wc)

2022-10-17 03:05 UTC, ethanckim commented on wloop_os/board/rpi4/post-build.sh
> +ssh-keygen -t rsa -N '' -f ./build/ssh/id_rsa -C build_generated_key <<< y
Added modifiers to ensure that passphrase prompt, overwrite prompt, and file location prompts are dealt with.

2022-10-17 03:08 UTC, ethanckim commented
@RyanJMah could you review the PR again please? Thank you.

2022-10-17 03:14 UTC, ethanckim commented
For the /etc/ssh/sshd_config, I think the default file generated and it's settings should be enough. Let me know if you think there is a value that should be adjusted specifically for our OS:
https://man7.org/linux/man-pages/man5/sshd_config.5.html

2022-11-01 00:51 UTC, Quinn1876 commented on wloop_os/board/rpi4/post-build.sh
> +chmod 600 $1/root/.ssh/authorized_keys
Please add a new `dev` user rather then direct root access. An article on how to do this is available here: https://linuxize.com/post/how-to-create-users-in-linux-using-the-useradd-command/

2022-11-01 00:52 UTC, Quinn1876 commented on wloop_os/board/rpi4/post-build.sh
> +chmod 600 $1/root/.ssh/authorized_keys
please give them permission to use sudo as well, we just don't want sudo context to be the default

2022-11-01 02:27 UTC, RyanJMah approved these changes
Double-check the `./build/ssh` directory. If that's good, it looks good to merge for me.

I will create a ticket for creating a non-root user in the buildroot config, with respect to @Quinn1876's comment.

2022-11-01 02:27 UTC, RyanJMah commented on wloop_os/board/rpi4/post-build.sh
> +chmod 600 $1/root/.ssh/authorized_keys
New users would have to be added in buildroot, but it is a good idea to have a non-root user. A new ticket for this would be appropriate I think.

2022-11-01 02:27 UTC, RyanJMah commented on wloop_os/board/rpi4/post-build.sh
> +mkdir -p ./build/ssh
I'm not sure if this would go in the correct directory. The keys should go in `./WLoopOS/build/` (the same directory that `sdcard.img` is copied into.

2022-11-02 23:51 UTC, merged